apiVersion: operator.kyma-project.io/v1alpha1
kind: ModuleTemplate
metadata:
  name: moduletemplate-istio
  namespace: kcp-system
  labels:
    "operator.kyma-project.io/managed-by": "lifecycle-manager"
    "operator.kyma-project.io/controller-name": "manifest"
    "operator.kyma-project.io/module-name": "istio"
  annotations:
    "operator.kyma-project.io/module-version": "0.0.1"
    "operator.kyma-project.io/module-provider": "internal"
    "operator.kyma-project.io/descriptor-schema-version": "v2"
spec:
  target: remote
  channel: regular
  data:
    apiVersion: install.istio.io/v1alpha1
    kind: IstioOperator
    metadata:
      namespace: istio-system
      name: istiocontrolplane
    spec:
      profile: demo
  descriptor:
    component:
      componentReferences: []
      name: kyma-project.io/istio
      provider: internal
      repositoryContexts:
      - baseUrl: ghcr.io/pbochynski/istio-module
        componentNameMapping: urlPath
        type: ociRegistry
      resources:
      - access:
          digest: sha256:d4cc98e2faf6f2e9df1f32ba1083dde7a701c35f49968566ecad94f24127b953
          type: localOciBlob
        name: istio
        relation: local
        type: helm-chart
        version: 0.0.1
      - access:
          digest: sha256:4889b67f5468d6505e46cfe37a509c40aca954d87145c19e9b9034674e5e8e4a
          type: localOciBlob
        name: config
        relation: local
        type: yaml
        version: 0.0.1
      sources:
      - access:
          commit: 185990585dde0186569f5fed955c4322c23e8456
          ref: refs/heads/main
          repoUrl: https://github.com/pbochynski/istio
          type: github
        name: istio
        type: git
        version: 0.0.1
      version: 0.0.1
    meta:
      schemaVersion: v2
